import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Proyectos históricos del Excel (1996-2016) - Total: 189 proyectos
const proyectosHistoricos = [
  {
    entidadContratante: 'JUEGOS ELECTRONICOS DE SUR',
    objetoContrato: 'Estructura cielo falso PETERLAND UNICO NEIVA',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 2811.0,
    areaM2: null,
    ubicacion: 'Neiva',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'INGENIO PROVIDENCIA S.A.',
    objetoContrato: 'CONST E INST CUBIERTA TEJA',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: null,
    areaM2: 929.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTROS COMERCIALES DEL CAFE S.AS',
    objetoContrato: 'Adecuación Royal Films UNICO NEIVA',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 280.0,
    areaM2: null,
    ubicacion: 'Neiva',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTROS COMERCIALES DE LA COSTA S.A.S',
    objetoContrato: 'Adecuación Royal Films UNICO BARRANQUILLA',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 100.0,
    areaM2: null,
    ubicacion: 'Barranquilla',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'BANCO DE OCCIDENTE',
    objetoContrato: 'Construcción de obra civiles, estructuras y cubiertas para la Ampliación C.C. UNICO TRES - Cali',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 780000.0,
    areaM2: 15900.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'PROCOCASA',
    objetoContrato: 'Remodelación Vacio central UNICO II',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 2487.23,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'UNION TEMPORAL EYR',
    objetoContrato: 'Construcción Puente Vehicular "La Paila"',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 293000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'UNION TEMPORAL EYR',
    objetoContrato: 'Barandas metálicas peatonales para puente El Jagual - Caloto',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 4259.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ROYAL FILMS S.A.S',
    objetoContrato: 'Construcción graderías y losas salas de cine UNICO NEIVA Y ADICIONALES',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 61463.0,
    areaM2: null,
    ubicacion: 'Neiva',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ROYAL FILMS S.A.S',
    objetoContrato: 'Construcción graderías y losas salas de cine C.C. LA ESTACION CALI',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 117639.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'INDUSTRIA MERCADEO Y COLOR SAS',
    objetoContrato: 'Mezanine local ESPRIT - LA ESTACION CALI',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 950.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'C.C. CONSTRUCCIONES S.A.S',
    objetoContrato: 'Estructura metálica Edificio Servicios Industriales (Equipos Auxiliares) POSTOBON Estructura Metálica cubiertas nueva sala de jarabes',
    fechaInicio: new Date('2016-01-01'),
    fechaFin: new Date('2016-12-31'),
    pesoKg: 138613.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ARBOLEDA ROJAS ANDRÉS',
    objetoContrato: 'Cali - Estructura Metálica Casa Zen',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 25000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL  ÚNICO',
    objetoContrato: 'PASTO - Parqueaderos y Cinemas, estructuras metálicas',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 255500.0,
    areaM2: 5148.0,
    ubicacion: 'Pasto',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO CORREDORES DE COMPETITIVIDAD',
    objetoContrato: 'La Sierra Cauca - Barandas Metálicas para Peatones Iglesia',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 2444.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'TUGO',
    objetoContrato: 'Cali - Estructura Metálica Bodega Muebles y Objetos',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 56958.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ROYAL FILMS SAS',
    objetoContrato: 'Pasto - Obras Civiles de Salas de Cine C.C Único Pasto',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: null,
    areaM2: 1000.0,
    ubicacion: 'Pasto',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Cubierta Doble Agua Planta de Pollos',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 1010.0,
    areaM2: null,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO DECEPAZ',
    objetoContrato: 'Cali - Estructura Metálica de Cubierta Centro de Salud DECEPAZ',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 7034.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ROYAL FILMS SAS',
    objetoContrato: 'Cali - Estructura Metálica para obras de Adecuación Salas de Cine C.C. Jardín Plaza',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 10650.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Taller Satélite',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 11189.0,
    areaM2: null,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Baños & Vestir',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 5450.0,
    areaM2: 545.0,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Planta de Harinas',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: null,
    areaM2: 800.0,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ESTRUMETAL',
    objetoContrato: 'Villarrica - Fabricación Estructura Metálica Bodega E42 Proyecto Hero Motors',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 114000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ROYAL FILMS SAS',
    objetoContrato: 'Yumbo - Obras Civiles Adecuación de Salas de Cine C.C Único Yumbo',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: null,
    areaM2: 800.0,
    ubicacion: 'Yumbo',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Barranquilla - Estructura Metálica Cuartos Fríos',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 6885.0,
    areaM2: null,
    ubicacion: 'Barranquilla',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'UNIÓN TEMPORAL E & R',
    objetoContrato: 'Corinto - Obra Civil y Traslado Puente El Jagua L=70 pies',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 70000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO REMIN – Nariño – Estructura Metálica Para Puente Frisoles, Ancuya – Ancusa, L=47 m',
    objetoContrato: 'CONSORCIO REMIN – Nariño – Estructura Metálica Para Puente Frisoles, Ancuya – Ancusa, L=47 m',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 89249.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA COLPATRIA – NEIVA – Estructura Metálicas Centro Comercial Único Neiva.',
    objetoContrato: 'CONSTRUCTORA COLPATRIA – NEIVA – Estructura Metálicas Centro Comercial Único Neiva.',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 583000.0,
    areaM2: 14140.0,
    ubicacion: 'Neiva',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ARINSA – POPAYAN – Cimentación, Estructura Metálica y Cubiertas Ampliación Centro Comercial Campanar',
    objetoContrato: 'ARINSA – POPAYAN – Cimentación, Estructura Metálica y Cubiertas Ampliación Centro Comercial Campanario',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 2454836.0,
    areaM2: 12000.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA COLPATRIA S.A. – BARRANQUILLA – Estructura Metálicas Centro Comercial Único Barranquill',
    objetoContrato: 'CONSTRUCTORA COLPATRIA S.A. – BARRANQUILLA – Estructura Metálicas Centro Comercial Único Barranquilla.',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 14984.0,
    areaM2: null,
    ubicacion: 'Barranquilla',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'AIRES MODERNOS S.A.S',
    objetoContrato: 'CONST E INST ESTRUCTURA PLATAFORMA DE EQUIPO AIRE',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 750.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ALMACENES ÉXITO S.A.',
    objetoContrato: 'CONST E INST ESTRUCTURA PLATAFORMA DE EQUIPO AIRE',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 1800.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTROS COMERCIALES DEL HUILA SAS',
    objetoContrato: 'CONTRAPISO LOCAL ROYAL FILMS C.C.UNICO NEIVA',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: null,
    areaM2: 1592.0,
    ubicacion: 'Neiva',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'JUAN MANUEL RODRIGUEZ -MEZANINE ALBERTO Vo5 UNICO NEIVA',
    objetoContrato: 'JUAN MANUEL RODRIGUEZ -MEZANINE ALBERTO Vo5 UNICO NEIVA',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 4150.0,
    areaM2: null,
    ubicacion: 'Neiva',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'SOCIEDAD DESARROLLOS INMOBILIARIOS',
    objetoContrato: 'ESTRUCT METALICA RAMPA PROVISIONAL UNICO BARRANQUILLA',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 4775.0,
    areaM2: null,
    ubicacion: 'Barranquilla',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'DISTRIBUIDORA INTERNACIONAL ARTICULOS',
    objetoContrato: 'MEZANINE LOCAL POLO',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: null,
    areaM2: 27.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO COLPATRIA ALPES CCA',
    objetoContrato: 'CONST E INST ESTRUCTURA WTC',
    fechaInicio: new Date('2015-01-01'),
    fechaFin: new Date('2015-12-31'),
    pesoKg: 247200.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'PARK PLAZA',
    objetoContrato: 'Cali - Estructura Metálica & Cubierta',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 30340.0,
    areaM2: 4620.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO CORREDORES DE COMPETITIVIDAD',
    objetoContrato: 'Barandas para puentes sector La Lupa - Cauca',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 13897.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA COLPATRIA',
    objetoContrato: 'Edificio World Trade Center Pacific, estructura metálica y cubierta',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 110139.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. ORLANDO REVELO',
    objetoContrato: 'Construcción puente vehicular "Frisoles" - Ancuyá Nariño                       Longitud 48 mts.',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 94484.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'MEJIA SANTANDER JUAN CARLOS',
    objetoContrato: 'Municipio Paez -Construcción Puentes Peatonales: El Cristo L=58m, El Buco L=39m y San Vicente L=126m',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: null,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Proyecto Pollo Campesino & Cuartos Fríos',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 148605.0,
    areaM2: null,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO APV',
    objetoContrato: 'Valledupar - Estructura Metálica y Cubierta Colegio Chiriqui',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 59388.0,
    areaM2: 2637.0,
    ubicacion: 'Valledupar',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'OBANDO LODOÑO JHON',
    objetoContrato: 'Laguna Seca - Estructura Metálica Casa',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 9836.0,
    areaM2: 256.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ARBOLEDA ROJAS ANDRÉS',
    objetoContrato: 'Cali - Estructura Metálica y Cubierta Locales Avenida Cañasgordas',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 12978.0,
    areaM2: 977.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'PELÁEZ HERNÁNDEZ MAURICIO',
    objetoContrato: 'Popayán - Estructura Metálica Dispensario Popayán',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 16199.0,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'INGENIO MAYAGÜEZ',
    objetoContrato: 'Estructura metálica para Edificio Torre',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 16239.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA HABITEK SAS',
    objetoContrato: 'Cali - Estructura Metálica Conjunto Residencial Lombar Día Club House',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 57142.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ROYAL FILMS SAS',
    objetoContrato: 'Cali - Estructura Metálica Soporte Graderías y Cuartos de Proyección Salas de Cine C.C Único Cali',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 123917.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Sala de Maquinas',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 15156.0,
    areaM2: 206.0,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Subestación Eléctrica',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 8956.0,
    areaM2: 142.0,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - 3 Niveles y Cubierta  Subproductos',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 23000.0,
    areaM2: 245.0,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - 3 Niveles y Cubierta  Subproductos',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 32071.0,
    areaM2: null,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL  ÚNICO',
    objetoContrato: 'YUMBO - Parqueaderos y cinemas',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 122000.0,
    areaM2: 1998.0,
    ubicacion: 'Yumbo',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCCIONES PROFORMAS',
    objetoContrato: 'Popayán - Cubierta Local Comercial Alberto VO5',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 9625.0,
    areaM2: 305.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Hangar Pollo en Pie',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 17391.0,
    areaM2: 1122.0,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Villagorgona - Cubierta Pasillo & Nuevo Casino',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 17391.0,
    areaM2: 747.0,
    ubicacion: 'Villagorgona',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO PIC',
    objetoContrato: 'Cali - Estructura Metálica para Bodega DIAN',
    fechaInicio: new Date('2014-01-01'),
    fechaFin: new Date('2014-12-31'),
    pesoKg: 17390.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL ÚNICO',
    objetoContrato: 'Diseño y construcción de centro comercial en Yumbo (Valle)',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 320000.0,
    areaM2: 9890.0,
    ubicacion: 'Yumbo',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'MAJA S.A.S.',
    objetoContrato: 'Estructura metálica y cubierta para el Coliseo Mundialista Korfball en Cali, Juegos Mundiales.',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 216000.0,
    areaM2: 3300.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO A.P.V.',
    objetoContrato: 'Estructura metálica y cubiertas para Colegio Chiriquí en Valledupar',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 52000.0,
    areaM2: 2650.0,
    ubicacion: 'Valledupar',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ASTRELEC S.A.S. Estructura metálica y cubierta para el edificio "Parque 102" en Cali',
    objetoContrato: 'ASTRELEC S.A.S. Estructura metálica y cubierta para el edificio "Parque 102" en Cali',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 14600.0,
    areaM2: 310.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL AUTOMOTRIZ',
    objetoContrato: 'Estructura metálica y cubierta local en Cali',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: null,
    areaM2: 273.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CRANE & SAFETY BUREAU S.A.S. Estructura metálica y cubierta en casa "Laguna Seca"',
    objetoContrato: 'Cali',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 15000.0,
    areaM2: 256.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL ÚNICO',
    objetoContrato: 'Estructuras metálicas , cubiertas y fachadas para ampliación en Cali',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 1800000.0,
    areaM2: 30000.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO 4a, ETAPA',
    objetoContrato: 'Estructuras metálicas y cubiertas  para bodegas y cuartos fríos - Cali',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: null,
    areaM2: 5325.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'INGENIO MAYAGUEZ',
    objetoContrato: 'Estructura metálica y cubierta para edificio "Torre Tacho" -  seis niveles -  altura 30 mts.',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 272000.0,
    areaM2: 345.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'INGENIO MAYAGUEZ',
    objetoContrato: 'Estructura metálica y cubierta para bodega Dúplex - altura 26 mts.',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 327000.0,
    areaM2: 4900.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ANDRÉS ARBOLEDA',
    objetoContrato: 'Estructura metálica y cubierta para locales "Cañas Gordas" . Cali',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 6170.0,
    areaM2: 517.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ABRAHAM STRELECK & ILLIAN COHEN',
    objetoContrato: 'Estructura metálica y cubierta edificio "Portal Plaza" en Cli',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 140000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. MAURICIO HOLGUÍN & Arq. MAURICIO HERZ',
    objetoContrato: 'Cubierta Dispensario Batallón Ejército en Popayán',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 16200.0,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. LUIS CARLOS RIOS',
    objetoContrato: 'P.Q.P PRODUCTOS QUÍMICOS PANAMERICANOS Estructura metálica y cubiertas en Cali',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: 30000.0,
    areaM2: 1050.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA PRODYGIO S.A.S. Estructura metálica y cubierta restaurante “La Lomita" en Popayán',
    objetoContrato: 'CONSTRUCTORA PRODYGIO S.A.S. Estructura metálica y cubierta restaurante “La Lomita" en Popayán',
    fechaInicio: new Date('2013-01-01'),
    fechaFin: new Date('2013-12-31'),
    pesoKg: null,
    areaM2: 656.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO CORREDORES DE COMPETITIVIDAD',
    objetoContrato: 'Diseño y construcción Puente Cusiyaco              Longitud 40 mts.',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 41000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. ALBERTO VIDAL',
    objetoContrato: 'Estructura metálica y cubierta par Morgue en Tuluá (Valle)',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: null,
    areaM2: 350.0,
    ubicacion: 'Tuluá',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COLEGIO FRANCISCANAS',
    objetoContrato: 'Diseño y construcción del Coliseo Cubierto No. 2 en Popayán',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: null,
    areaM2: 750.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COMFACAUCA',
    objetoContrato: 'Diseño y construcción de estructuras y cubiertas par canchas Centro Recreativo Pisojé.',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: null,
    areaM2: 2470.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ALMACEN CARREFOUR',
    objetoContrato: 'Diseño uy construcción de mezaninne en Pasto (Nariño)',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: null,
    areaM2: 870.0,
    ubicacion: 'Pasto',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COMFACAUCA',
    objetoContrato: 'Diseño y construcción de mezaninne para oficinas sede de Popayán',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: null,
    areaM2: 216.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO MJ 2011',
    objetoContrato: 'Coliseo de fútbol sala para los Juegos Nacionales de Popayán',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 267500.0,
    areaM2: 6133.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ARGEU S.A.',
    objetoContrato: 'Coliseo de Artes Marciales para los Juegos Nacionales de Popayán',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 196000.0,
    areaM2: 4036.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'FONDO MIXTO PARA PROMOCIÓN DEL DEPORTE- Diseño y construcción estructura metálica y cubierta para la',
    objetoContrato: 'FONDO MIXTO PARA PROMOCIÓN DEL DEPORTE- Diseño y construcción estructura metálica y cubierta para la piscina olímpica, Juegos Nacionales de Popayán',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 135000.0,
    areaM2: 3557.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ings. CELY y CAICEDO',
    objetoContrato: 'Estructura metálica y cubierta edificio PRADO 2 en Popayán',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 14990.0,
    areaM2: 220.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'INGENIO MANUELITA',
    objetoContrato: 'Estructura metálica para edificio de 6 plantas, sector de mezclas en Palmira (Valle)',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 72000.0,
    areaM2: 703.0,
    ubicacion: 'Palmira',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO 3A. ETAPA',
    objetoContrato: 'Estructura metálica y  cubierta en ampliación',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: null,
    areaM2: 3170.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COMFACAUCA',
    objetoContrato: 'Diseño y construcción puente vehicular sobre rio Cauca Centro Recreativo Pisojé Longitud 40 mts.',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 20000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL ÚNICO',
    objetoContrato: 'Diseño y construcción de estructuras metálicas y cubiertas, en Villavicencio',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 670000.0,
    areaM2: 16300.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO CORREDORES DE COMPETITIVIDAD',
    objetoContrato: 'Diseño  y construcción puente vehicular en Arco,  Saraconcho     Longitud 150 mts.',
    fechaInicio: new Date('2012-01-01'),
    fechaFin: new Date('2012-12-31'),
    pesoKg: 357000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'I.C.B.F. Estructuras metálicas y cubiertas en Guapi y El Bordo, Depto, del Cauca',
    objetoContrato: 'I.C.B.F. Estructuras metálicas y cubiertas en Guapi y El Bordo, Depto, del Cauca',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: null,
    areaM2: 883.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'EKA S.A. Estructuras metálicas  y entrepisos para la ampliación de la fábrica en Cali',
    objetoContrato: 'EKA S.A. Estructuras metálicas  y entrepisos para la ampliación de la fábrica en Cali',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: 15000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'FERRETERIA MARACAIBO',
    objetoContrato: 'Estructura metálica mezaninne para bodega de cemento en Popayán',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: null,
    areaM2: 180.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'VARELA FIHOLL & CIA. LTDA. Estructura metálica, cubiertas y carpintería metálica Colegio Matamoros P',
    objetoContrato: 'VARELA FIHOLL & CIA. LTDA. Estructura metálica, cubiertas y carpintería metálica Colegio Matamoros Popayán',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: null,
    areaM2: 2770.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ODINSA S.A.',
    objetoContrato: 'Diseño y construcción puente peatonal Romelia 1 en Risaralda - Autopistas del Café. Long. 130 mts.',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: 59000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ODINSA S.A. Diseño y construcción puente peatonal Romelia 2 en Dosquebradas Risaralda  Longitud 212 ',
    objetoContrato: 'ODINSA S.A. Diseño y construcción puente peatonal Romelia 2 en Dosquebradas Risaralda  Longitud 212 mts.',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: 92000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO VIAS DE CALI S.A.S. Diseño y construcción   puente peatonal Autopista Sur x Carrera 63B de',
    objetoContrato: 'CONSORCIO VIAS DE CALI S.A.S. Diseño y construcción   puente peatonal Autopista Sur x Carrera 63B de Cali',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: 128000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO VIAS DE CALI S.A.S. Diseño y construcción puente peatonal Autopista Sur x Carrera 68 de Ca',
    objetoContrato: 'CONSORCIO VIAS DE CALI S.A.S. Diseño y construcción puente peatonal Autopista Sur x Carrera 68 de Cali',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: 170450.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COMFACAUCA',
    objetoContrato: 'Cubierta en teja Standing Seam para el Colegio de Puerto Tejada (Cauca)',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: null,
    areaM2: 758.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CALIMA MOTORS',
    objetoContrato: 'Estructura metálica y cubierta para bodegas en Buenaventura (Valle)',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: null,
    areaM2: 1370.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL ÚNICO PASTO',
    objetoContrato: 'Estructuras metálicas y cubiertas en teja Standing Seam para sede de Pasto.',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: 410000.0,
    areaM2: 18820.0,
    ubicacion: 'Pasto',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COMFACAUCA',
    objetoContrato: 'Estructura metálica y cubierta Colegio Jardín Social El Mirador, Popayán',
    fechaInicio: new Date('2011-01-01'),
    fechaFin: new Date('2011-12-31'),
    pesoKg: null,
    areaM2: 1900.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COMFACAUCA',
    objetoContrato: 'Estructura metálica y cubierta Obra Jardín Social en Popayán',
    fechaInicio: new Date('2010-01-01'),
    fechaFin: new Date('2010-12-31'),
    pesoKg: null,
    areaM2: 1345.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO M.G. Puente vehicular metálico sobre el río Mazamorras (Cauca/Huila) Longitud 45 mts.',
    objetoContrato: 'CONSORCIO M.G. Puente vehicular metálico sobre el río Mazamorras (Cauca/Huila) Longitud 45 mts.',
    fechaInicio: new Date('2010-01-01'),
    fechaFin: new Date('2010-12-31'),
    pesoKg: 63000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. MANUEL MUÑOZ',
    objetoContrato: 'Reparación y montaje puente peatonal Terminal de Transportes de Popayán  Longitud 70 mts.',
    fechaInicio: new Date('2010-01-01'),
    fechaFin: new Date('2010-12-31'),
    pesoKg: 57000.0,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO SANTANDER 3',
    objetoContrato: 'Estructuras metálicas varias Matadero de Santander de Quilichao',
    fechaInicio: new Date('2010-01-01'),
    fechaFin: new Date('2010-12-31'),
    pesoKg: 34000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COLEGIO COLOMBO FRANCES',
    objetoContrato: 'POPAYÁN Coliseo Cubierto para el Colegio',
    fechaInicio: new Date('2010-01-01'),
    fechaFin: new Date('2010-12-31'),
    pesoKg: null,
    areaM2: 896.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL ÚNICO',
    objetoContrato: 'BARRANQUILLA - Diseño y construcción estructura metálica y cubierta',
    fechaInicio: new Date('2009-01-01'),
    fechaFin: new Date('2009-12-31'),
    pesoKg: 625770.0,
    areaM2: 21984.0,
    ubicacion: 'Barranquilla',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ZONA FRANCA PALMASECA',
    objetoContrato: 'Estructura metálica para cubierta de bodegas',
    fechaInicio: new Date('2009-01-01'),
    fechaFin: new Date('2009-12-31'),
    pesoKg: 22500.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA CARPOL LTDA.',
    objetoContrato: 'Estructuras metálicas y cubiertas Colegio Potrerogrande en Cali',
    fechaInicio: new Date('2009-01-01'),
    fechaFin: new Date('2009-12-31'),
    pesoKg: null,
    areaM2: 2800.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO DEL CAUCA',
    objetoContrato: 'Diseño y construcción Puente Vehicular "Nolasco" sobre el río Páez        Longitud 145 mts.',
    fechaInicio: new Date('2009-01-01'),
    fechaFin: new Date('2009-12-31'),
    pesoKg: 350000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ESTACIÓN MARBELLA -Estructura metálica para la Estación de Servicio en Cali.',
    objetoContrato: 'ESTACIÓN MARBELLA -Estructura metálica para la Estación de Servicio en Cali.',
    fechaInicio: new Date('2009-01-01'),
    fechaFin: new Date('2009-12-31'),
    pesoKg: null,
    areaM2: 1400.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'O.P.P. GRANELES',
    objetoContrato: 'Estructuras metálicas para bodegas en Buenaventura (Valle del Cauca)',
    fechaInicio: new Date('2009-01-01'),
    fechaFin: new Date('2009-12-31'),
    pesoKg: 66730.0,
    areaM2: null,
    ubicacion: 'Buenaventura',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ARINSA S.A. Diseño y construcción estructuras metálicas y cubiertas Centro Comercial Campanario',
    objetoContrato: 'Popayán',
    fechaInicio: new Date('2008-01-01'),
    fechaFin: new Date('2008-12-31'),
    pesoKg: 470000.0,
    areaM2: 22000.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'TERMINAL DE TRNSPORTES POPAYÁN',
    objetoContrato: 'Cubierta muelle de embarque',
    fechaInicio: new Date('2008-01-01'),
    fechaFin: new Date('2008-12-31'),
    pesoKg: 28000.0,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COMITÉ CAFETEROS CAUCA',
    objetoContrato: 'Estructura metálica Coliseo  Cubierto  Timbío',
    fechaInicio: new Date('2008-01-01'),
    fechaFin: new Date('2008-12-31'),
    pesoKg: 18500.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'NUTRIPLANTAS',
    objetoContrato: 'Estructura metálica de cubierta en bodega de Tuluá',
    fechaInicio: new Date('2008-01-01'),
    fechaFin: new Date('2008-12-31'),
    pesoKg: 94000.0,
    areaM2: 4800.0,
    ubicacion: 'Tuluá',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CLINICA EXCELLENCE',
    objetoContrato: 'Estructura metálica para ampliación de la Clínica en Cali',
    fechaInicio: new Date('2008-01-01'),
    fechaFin: new Date('2008-12-31'),
    pesoKg: 15500.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'DISCOTECA CUCARA-MACARA',
    objetoContrato: 'Estructura metálica de cubierta en Yumbo (Valle)',
    fechaInicio: new Date('2008-01-01'),
    fechaFin: new Date('2008-12-31'),
    pesoKg: 20000.0,
    areaM2: 800.0,
    ubicacion: 'Yumbo',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA HERNANDEZ BOHMER',
    objetoContrato: 'Estructura metálica edificio Campestre Towers Cali',
    fechaInicio: new Date('2007-01-01'),
    fechaFin: new Date('2007-12-31'),
    pesoKg: 16000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CALDERON Y JARAMILLO INGS.',
    objetoContrato: 'Estructura de Cubierta para Estación de Servicio en Manizales',
    fechaInicio: new Date('2007-01-01'),
    fechaFin: new Date('2007-12-31'),
    pesoKg: 9700.0,
    areaM2: null,
    ubicacion: 'Manizales',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA CARPOL',
    objetoContrato: 'Estructuras metálicas varias Conjunto Residencial Campo Real en Popayán',
    fechaInicio: new Date('2007-01-01'),
    fechaFin: new Date('2007-12-31'),
    pesoKg: 19000.0,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'VELKAR S.A. Estructura metálica de cubierta para bodega  de TEXCINTAS en Cali',
    objetoContrato: 'VELKAR S.A. Estructura metálica de cubierta para bodega  de TEXCINTAS en Cali',
    fechaInicio: new Date('2007-01-01'),
    fechaFin: new Date('2007-12-31'),
    pesoKg: 24000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: '2A. Etapa. Estructuras metálicas varias',
    fechaInicio: new Date('2007-01-01'),
    fechaFin: new Date('2007-12-31'),
    pesoKg: 15000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ALPICAL',
    objetoContrato: 'Estructuras metálicas fábrica Caloto Cauca',
    fechaInicio: new Date('2007-01-01'),
    fechaFin: new Date('2007-12-31'),
    pesoKg: 8800.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CENTRO COMERCIAL ÚNICO CALI- 4a. Etapa',
    objetoContrato: 'Estructuras metálicas varias',
    fechaInicio: new Date('2007-01-01'),
    fechaFin: new Date('2007-12-31'),
    pesoKg: 60000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'SUPERMERCADOS POMONA Estructura metálica y cubierta Ciudad Jardín',
    objetoContrato: 'Cali',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: 29000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'MUNICIPIO DE MIRNDA',
    objetoContrato: 'CAUCA. Diseño y construcción Coliseo Cubierto Plaza Principal',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: null,
    areaM2: 1912.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'D.C.I. ARTE',
    objetoContrato: 'Estructuras y cubierta sede Cali',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: 15000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Arq. JAIME CÁRDENAS Y ASOCS. Estructuras metálicas en Universidad San Buenaventura de Cali',
    objetoContrato: 'Arq. JAIME CÁRDENAS Y ASOCS. Estructuras metálicas en Universidad San Buenaventura de Cali',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: 12000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COLEGIO COLOMBO BRITÁNICO',
    objetoContrato: 'Estructura de Cubierta en sede de Cali',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: null,
    areaM2: 220.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA MELENDEZ',
    objetoContrato: 'Estructura metálica cubierta Clubhouse Urbanización Palmera Real de Cali.',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: null,
    areaM2: 300.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CLINICA EXCELLENCE CALI',
    objetoContrato: 'Estructura básica de soporte edificio de 4 plantas',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: 55000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'POLLOS BUCANERO',
    objetoContrato: 'Estructura metálica mezaninne y escalera de acceso',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: 5800.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'INCICO LTDA. Diseño y construcción estructura metálica bodega Cementos Argos en Yumbo Valle del Cauc',
    objetoContrato: 'INCICO LTDA. Diseño y construcción estructura metálica bodega Cementos Argos en Yumbo Valle del Cauca',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: null,
    areaM2: 480.0,
    ubicacion: 'Yumbo',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'VELKAR S.A.  Estructura metálica de cubierta y de soporte 3a. Etapa Centro Comercial Único',
    objetoContrato: 'Cali',
    fechaInicio: new Date('2006-01-01'),
    fechaFin: new Date('2006-12-31'),
    pesoKg: null,
    areaM2: 4000.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO ACUANORTE',
    objetoContrato: 'Instalación 1.800 mts. Tubería de hierro dúctil acueducto del río Palacé y diseño y construcción de 5 viaductos metálicos.           Longitud 130 mts.',
    fechaInicio: new Date('2005-01-01'),
    fechaFin: new Date('2005-12-31'),
    pesoKg: null,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. JUAN CARLOS CANENCIO',
    objetoContrato: 'Estructura metálica para Plaza de Mercado Villarrica Cauca',
    fechaInicio: new Date('2005-01-01'),
    fechaFin: new Date('2005-12-31'),
    pesoKg: null,
    areaM2: 600.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA PIJAO LTDA. Construcción de 14 puentes metálicos en apartamentos',
    objetoContrato: 'Cali.    Longitud 58.80 mts.',
    fechaInicio: new Date('2005-01-01'),
    fechaFin: new Date('2005-12-31'),
    pesoKg: 52000.0,
    areaM2: null,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'PROGRAMA TIERRADENTRO',
    objetoContrato: 'UNIÓN EUROPEA - Diseño y construcción puentes peatonales y caballares en Mosoco, Calderas y Cohetando, Depto. Del Cauca.  Longitud 45 mts.',
    fechaInicio: new Date('2005-01-01'),
    fechaFin: new Date('2005-12-31'),
    pesoKg: 15000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'VELKAR S.A.',
    objetoContrato: 'Diseño y construcción estructuras metálicas para fábrica TEXCINTAS S.A. en Cali',
    fechaInicio: new Date('2005-01-01'),
    fechaFin: new Date('2005-12-31'),
    pesoKg: null,
    areaM2: 800.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'VELKAR S.A.  Cubiertas parqueaderos edificio Plazuela del Sur en Cali',
    objetoContrato: 'VELKAR S.A.  Cubiertas parqueaderos edificio Plazuela del Sur en Cali',
    fechaInicio: new Date('2005-01-01'),
    fechaFin: new Date('2005-12-31'),
    pesoKg: null,
    areaM2: 550.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COLEGIO STA. ISABEL DE HUNGRIA',
    objetoContrato: 'Estructura básica y de cubierta , obra civil y acabados en Sede Cali Ciudad 2000',
    fechaInicio: new Date('2005-01-01'),
    fechaFin: new Date('2005-12-31'),
    pesoKg: null,
    areaM2: 1200.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'MIRA TU SALUD EPS. Reforzamiento edificio de 5 plantas en Bogotá y obras metálicas varias',
    objetoContrato: 'MIRA TU SALUD EPS. Reforzamiento edificio de 5 plantas en Bogotá y obras metálicas varias',
    fechaInicio: new Date('2005-01-01'),
    fechaFin: new Date('2005-12-31'),
    pesoKg: null,
    areaM2: 1200.0,
    ubicacion: 'Bogotá',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ACUEDUCTO Y ALCANTARILLADO DE POPAYÁN S.A. Diseño y construcción viaducto para soportar tubería PVC ',
    objetoContrato: 'ACUEDUCTO Y ALCANTARILLADO DE POPAYÁN S.A. Diseño y construcción viaducto para soportar tubería PVC de 1200 mm                                       Longitud 27,50 mts',
    fechaInicio: new Date('2004-01-01'),
    fechaFin: new Date('2004-12-31'),
    pesoKg: null,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'PROGRAMA TIERRADENTRO . UNIÓN EUROPEA -Diseño y construcción puentes peatonales y caballares en Yaqu',
    objetoContrato: 'PROGRAMA TIERRADENTRO . UNIÓN EUROPEA -Diseño y construcción puentes peatonales y caballares en Yaquivá, Segovia, Carrizales y La Estrella (Cauca) Longitud 94 mts.',
    fechaInicio: new Date('2004-01-01'),
    fechaFin: new Date('2004-12-31'),
    pesoKg: 30000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONTORCIÓ CONCONCRETO RAMON H. ALMACEN ÉXITO Estructura metálica y obras complementarias Ampliación.',
    objetoContrato: 'CONTORCIÓ CONCONCRETO RAMON H. ALMACEN ÉXITO Estructura metálica y obras complementarias Ampliación.',
    fechaInicio: new Date('2004-01-01'),
    fechaFin: new Date('2004-12-31'),
    pesoKg: null,
    areaM2: 1715.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'COLEGIO STA. ISABEL DE HUNGRÍA',
    objetoContrato: 'CALI diseño y construcción de estructura metálica para Coliseo Deportivo Dúplex en la ciudad de Cali.',
    fechaInicio: new Date('2003-01-01'),
    fechaFin: new Date('2003-12-31'),
    pesoKg: null,
    areaM2: 1650.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCCIONES E INGENIERÍA LTDA.',
    objetoContrato: 'Viaductos para soportar tuberías 500 mm Ingenio Providencia Valle del Cauca                                                      Longitud 70 mts.',
    fechaInicio: new Date('2003-01-01'),
    fechaFin: new Date('2003-12-31'),
    pesoKg: null,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. ÁLVARO CARVAJAL',
    objetoContrato: 'Estructura metálica de cubierta para Centro de Acopio en La Vega - Cauca.',
    fechaInicio: new Date('2003-01-01'),
    fechaFin: new Date('2003-12-31'),
    pesoKg: null,
    areaM2: 1100.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'FERTECNICA S.A.',
    objetoContrato: 'Puente vehicular en vigas metálicas y losa de concreto sobre Metaldeck  carretera Tacueyó- López Depto. Del Cauca.                        Longitud 12 mts.',
    fechaInicio: new Date('2003-01-01'),
    fechaFin: new Date('2003-12-31'),
    pesoKg: 15000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'IGLESIA DE DIOS MINISTERIAL',
    objetoContrato: 'POPAYÁN - estructura metálica de cubierta.',
    fechaInicio: new Date('2003-01-01'),
    fechaFin: new Date('2003-12-31'),
    pesoKg: null,
    areaM2: 1200.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'UNIÓN TEMPORAL CENTRO COMERCIAL POPULAR. Estructura para Centro Comercial en Pasto',
    objetoContrato: 'UNIÓN TEMPORAL CENTRO COMERCIAL POPULAR. Estructura para Centro Comercial en Pasto',
    fechaInicio: new Date('2003-01-01'),
    fechaFin: new Date('2003-12-31'),
    pesoKg: null,
    areaM2: 665.0,
    ubicacion: 'Pasto',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ings. AURA TULIA URBANO, REGINA SOLARTE y EDUARDO CASTRILLON, estructuras metálicas para Coliseos de',
    objetoContrato: 'Ings. AURA TULIA URBANO, REGINA SOLARTE y EDUARDO CASTRILLON, estructuras metálicas para Coliseos del Plan Colombia en Almaguer,Cajibío, Morales, Caldono y Florencia- Depto. Del Cauca',
    fechaInicio: new Date('2002-01-01'),
    fechaFin: new Date('2002-12-31'),
    pesoKg: 231000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONCRECAUCA LTDA. Estructuras metálicas, silos y pavimento de concreto, planta de Prefabricados en P',
    objetoContrato: 'CONCRECAUCA LTDA. Estructuras metálicas, silos y pavimento de concreto, planta de Prefabricados en Puerto Tejada, Cauca',
    fechaInicio: new Date('2002-01-01'),
    fechaFin: new Date('2002-12-31'),
    pesoKg: null,
    areaM2: 1532.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'In. HERNAN VALLEJO',
    objetoContrato: 'Puente peatonal "Sesecito" en Timbiquí Cauca.                                         Longitud 22 mts.',
    fechaInicio: new Date('2002-01-01'),
    fechaFin: new Date('2002-12-31'),
    pesoKg: 10000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. JESUS ALBEIRO VASQUEZ',
    objetoContrato: 'Puente colgante sobre el río El Molino, Paispamba Cauca     Longitud 25 mts.',
    fechaInicio: new Date('2002-01-01'),
    fechaFin: new Date('2002-12-31'),
    pesoKg: 12000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. JORGE PALECHOR',
    objetoContrato: 'Puente peatonal colgante río Dos Brazos en Popayán                          Longitud 28 mts.',
    fechaInicio: new Date('2002-01-01'),
    fechaFin: new Date('2002-12-31'),
    pesoKg: 12000.0,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. HERNAN VALLEJO',
    objetoContrato: 'estructura metálica Hospital de Timbiquí, Cauca.',
    fechaInicio: new Date('2002-01-01'),
    fechaFin: new Date('2002-12-31'),
    pesoKg: null,
    areaM2: 520.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'GOBERNACIÓN DEL CAUCA',
    objetoContrato: 'Dos esculturas “Tierradentro”',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: 16130.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'READY FRUIT COMPANY',
    objetoContrato: 'Estructura metálica de cubierta  y entrepisos, Planta de La Unión, Valle del Cauca',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: null,
    areaM2: 3579.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CALDERON Y JARAMILLO INGS.',
    objetoContrato: 'Estructura metálica para fábrica de quesos Delvechio - Bogotá',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: null,
    areaM2: 3322.0,
    ubicacion: 'Bogotá',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'VIDRIOS Y ALUMINIOS ELSOL',
    objetoContrato: 'Estructura metálica para fábrica en Popayán.',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: null,
    areaM2: 663.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CORPORACIÓN NASA KIWE',
    objetoContrato: 'Puente vehicular quebrada "El Lucero" Tierradentro Cauca.         Longitud : 16 mts.',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: 30000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'J.M.D. CONSTRUCCIÓN LTDA. Construcción dos puentes vehiculares Cartón de Colombia, Cauca. Longitud 2',
    objetoContrato: 'J.M.D. CONSTRUCCIÓN LTDA. Construcción dos puentes vehiculares Cartón de Colombia, Cauca. Longitud 20 mts.',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: 30000.0,
    areaM2: null,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CALDERON Y JARAMILLO INGS.',
    objetoContrato: 'Refuerzo puente vehicular Cameguadua, Chinchiná, Caldas        longitud 10 mts.',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: 15000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSORCIO Q.M. SAN ISIDRO',
    objetoContrato: 'Construcción estructuras metálicas y rejas de seguridad, Penitenciaría San Isidro Popayán Cauca',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: null,
    areaM2: 2376.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. JUAN CARLOS CANENCIO',
    objetoContrato: 'Estructura metálica para Plaza de Mercado en Corinto Cauca.',
    fechaInicio: new Date('2001-01-01'),
    fechaFin: new Date('2001-12-31'),
    pesoKg: null,
    areaM2: 4115.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. DIEGO CARVAJAL',
    objetoContrato: 'Estructura metálica edificio Banco Coopdesarrollo en Jamundí',
    fechaInicio: new Date('2000-01-01'),
    fechaFin: new Date('2000-12-31'),
    pesoKg: null,
    areaM2: 300.0,
    ubicacion: 'Jamundí',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. RICARDO ARBOLEDA',
    objetoContrato: 'Estructuras metálicas para  bodegas C.I. Valle',
    fechaInicio: new Date('2000-01-01'),
    fechaFin: new Date('2000-12-31'),
    pesoKg: null,
    areaM2: 1320.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'FONDO NAL. CAMINOS VECINALES',
    objetoContrato: 'Diseño y construcción de dos puentes peatonales en San José del Palmar Departamento del Chocó               longitud : 37 mts.',
    fechaInicio: new Date('2000-01-01'),
    fechaFin: new Date('2000-12-31'),
    pesoKg: 20000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. ANDRÉS CASTRILLÓN',
    objetoContrato: 'Soportes metálicos para conducción acueducto Pílamo -Caloto  longitud 800 mts.',
    fechaInicio: new Date('2000-01-01'),
    fechaFin: new Date('2000-12-31'),
    pesoKg: null,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Constructora Carpol',
    objetoContrato: 'Carpintería metálica y cerramiento para Urbanización Villa del Viento - Popayán 400 viviendas',
    fechaInicio: new Date('2000-01-01'),
    fechaFin: new Date('2000-12-31'),
    pesoKg: null,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CALDERON & JARAMILLO',
    objetoContrato: 'Estructuras básicas y de cubierta para el Condominio "Costa Esmeralda" en Panamá.',
    fechaInicio: new Date('2000-01-01'),
    fechaFin: new Date('2000-12-31'),
    pesoKg: null,
    areaM2: 2000.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'Ing. JUAN CARLOS MEJÍA',
    objetoContrato: 'Estructura metálica Plaza de Mercado en Guapi, Depto. Del Cauca',
    fechaInicio: new Date('2000-01-01'),
    fechaFin: new Date('2000-12-31'),
    pesoKg: null,
    areaM2: 520.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'YAZAKI METREX S.A.',
    objetoContrato: 'Estructura metálica cubierta para fábrica en el Parque Industrial Popayán',
    fechaInicio: new Date('1999-01-01'),
    fechaFin: new Date('1999-12-31'),
    pesoKg: null,
    areaM2: 3000.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'AROMA DEL CAUCA',
    objetoContrato: 'Estructura metálica cubierta para fábrica en el Parque Industrial Popayán',
    fechaInicio: new Date('1999-01-01'),
    fechaFin: new Date('1999-12-31'),
    pesoKg: null,
    areaM2: 1790.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'MUNICIPIO DE GUAPI',
    objetoContrato: 'Puente sobre el río Napi para conducción tubería  de acueducto       longitud 117 mts.',
    fechaInicio: new Date('1999-01-01'),
    fechaFin: new Date('1999-12-31'),
    pesoKg: 25000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CORPORACIÓN NASA KIWE',
    objetoContrato: 'Construcción de vigas, pen- dolones y suministro cables para puente colgante vehicular  La Troja en Tierradentro.         Longitud 103 mts.',
    fechaInicio: new Date('1999-01-01'),
    fechaFin: new Date('1999-12-31'),
    pesoKg: 35000.0,
    areaM2: null,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'MUNICIPIO DE POPAYÁN',
    objetoContrato: 'Puente peatonal sobre el río Molino, sector Universidad-Hospital.    Longitud 18 mts.',
    fechaInicio: new Date('1999-01-01'),
    fechaFin: new Date('1999-12-31'),
    pesoKg: 12000.0,
    areaM2: null,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'MADECONS LTDA. Diseño y construcción de dos puentes metálicos, carretera circunvalar Pasto  Longitud',
    objetoContrato: 'MADECONS LTDA. Diseño y construcción de dos puentes metálicos, carretera circunvalar Pasto  Longitud 25 mts c/u.',
    fechaInicio: new Date('1999-01-01'),
    fechaFin: new Date('1999-12-31'),
    pesoKg: 80000.0,
    areaM2: null,
    ubicacion: 'Pasto',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'CONSTRUCTORA AYACAR S.A',
    objetoContrato: 'Estructuras metálicas de cubierta y entrepisos Edificio Droguería Humanitaria de Cali',
    fechaInicio: new Date('1999-01-01'),
    fechaFin: new Date('1999-12-31'),
    pesoKg: null,
    areaM2: 770.0,
    ubicacion: 'Cali',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'PARROQUIA NIÑO JESÚS DE PRAGA',
    objetoContrato: 'Santander de Quilichao - Cubierta metálica iglesia Parroquial',
    fechaInicio: new Date('1999-01-01'),
    fechaFin: new Date('1999-12-31'),
    pesoKg: null,
    areaM2: 600.0,
    ubicacion: 'Colombia',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'MUNICIPIO DE POPAYÁN, GOBERNACIÓN DEL CAUCA Y OTRAS ENTIDADES',
    objetoContrato: 'Diseño y construcción de Coliseos Polideportivos en los barrios Palacé, Alfonso López, La Esmeralda, Pandiguando, Chuni, Colegio Negret, Berlín, Sauces, Independencia y La Paz',
    fechaInicio: new Date('1998-01-01'),
    fechaFin: new Date('1998-12-31'),
    pesoKg: null,
    areaM2: 8650.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'ENTIDADES DE ORDEN DEPARTAMENTAL Y MUNICIPAL Diseño y Construcción de Coliseos Polideportivos en San',
    objetoContrato: 'ENTIDADES DE ORDEN DEPARTAMENTAL Y MUNICIPAL Diseño y Construcción de Coliseos Polideportivos en Santa Rosa, Piendamó, Corinto, La Sierra, Timbiquí y Santander de Quilichao (Cauca) y Tumaco (Nariño)',
    fechaInicio: new Date('1998-01-01'),
    fechaFin: new Date('1998-12-31'),
    pesoKg: null,
    areaM2: 9000.0,
    ubicacion: 'Cauca',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'GUIDO GAVILANES Y OSCAR RUIZ',
    objetoContrato: 'Diseño y construcción de estructuras metálicas para tres bodegas  en el Parque Industrial de Popayán',
    fechaInicio: new Date('1998-01-01'),
    fechaFin: new Date('1998-12-31'),
    pesoKg: null,
    areaM2: 1400.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'LOTERÍA DEL CAUCA',
    objetoContrato: 'Diseño y construcción estructuras  metálicas para el Edificio Edgar Negret Popayán',
    fechaInicio: new Date('1998-01-01'),
    fechaFin: new Date('1998-12-31'),
    pesoKg: null,
    areaM2: 545.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'UNIVERSIDAD DEL CAUCA',
    objetoContrato: 'Diseño y construcción Coliseo Cubierto en el Campus de Popayán',
    fechaInicio: new Date('1998-01-01'),
    fechaFin: new Date('1998-12-31'),
    pesoKg: null,
    areaM2: 1632.0,
    ubicacion: 'Popayán',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
  {
    entidadContratante: 'FRIESLAND COLOMBIA S.A.',
    objetoContrato: 'Diseño y construcción de la  estructura metálica y cubierta para planta de producción en Pasto',
    fechaInicio: new Date('1996-01-01'),
    fechaFin: new Date('1996-12-31'),
    pesoKg: null,
    areaM2: 611.0,
    ubicacion: 'Pasto',
    departamento: null,
    valorContrato: 0,
    visible: true,
    destacado: false,
    orden: 0
  },
]

async function main() {
  console.log('🌱 Agregando proyectos históricos (1996-2016)...')
  
  let count = 0
  for (const proyecto of proyectosHistoricos) {
    await prisma.proyectoHojaVida.create({ data: proyecto })
    count++
  }
  
  console.log(`✅ ${count} proyectos históricos agregados`)
  console.log('🎉 Seed de proyectos históricos completado!')
  
  const total = await prisma.proyectoHojaVida.count()
  console.log(`📊 Total de proyectos en BD: ${total}`)
}

main()
  .catch((e) => {
    console.error('❌ Error en seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

