export interface ColombiaCity {
  nombre: string
  departamento: string
}

// Capitales departamentales + ciudades industriales/medianas relevantes para construcción.
export const COLOMBIA_CITIES: ColombiaCity[] = [
  { nombre: "Bogotá", departamento: "Cundinamarca" },
  { nombre: "Medellín", departamento: "Antioquia" },
  { nombre: "Cali", departamento: "Valle del Cauca" },
  { nombre: "Barranquilla", departamento: "Atlántico" },
  { nombre: "Cartagena", departamento: "Bolívar" },
  { nombre: "Cúcuta", departamento: "Norte de Santander" },
  { nombre: "Bucaramanga", departamento: "Santander" },
  { nombre: "Pereira", departamento: "Risaralda" },
  { nombre: "Santa Marta", departamento: "Magdalena" },
  { nombre: "Ibagué", departamento: "Tolima" },
  { nombre: "Manizales", departamento: "Caldas" },
  { nombre: "Pasto", departamento: "Nariño" },
  { nombre: "Neiva", departamento: "Huila" },
  { nombre: "Villavicencio", departamento: "Meta" },
  { nombre: "Armenia", departamento: "Quindío" },
  { nombre: "Popayán", departamento: "Cauca" },
  { nombre: "Valledupar", departamento: "Cesar" },
  { nombre: "Montería", departamento: "Córdoba" },
  { nombre: "Sincelejo", departamento: "Sucre" },
  { nombre: "Tunja", departamento: "Boyacá" },
  { nombre: "Riohacha", departamento: "La Guajira" },
  { nombre: "Quibdó", departamento: "Chocó" },
  { nombre: "Florencia", departamento: "Caquetá" },
  { nombre: "Yopal", departamento: "Casanare" },
  { nombre: "Mocoa", departamento: "Putumayo" },
  { nombre: "Arauca", departamento: "Arauca" },
  { nombre: "Mitú", departamento: "Vaupés" },
  { nombre: "Inírida", departamento: "Guainía" },
  { nombre: "Puerto Carreño", departamento: "Vichada" },
  { nombre: "San José del Guaviare", departamento: "Guaviare" },
  { nombre: "Leticia", departamento: "Amazonas" },
  { nombre: "San Andrés", departamento: "San Andrés y Providencia" },
  // Ciudades intermedias e industriales
  { nombre: "Soacha", departamento: "Cundinamarca" },
  { nombre: "Soledad", departamento: "Atlántico" },
  { nombre: "Bello", departamento: "Antioquia" },
  { nombre: "Itagüí", departamento: "Antioquia" },
  { nombre: "Envigado", departamento: "Antioquia" },
  { nombre: "Sabaneta", departamento: "Antioquia" },
  { nombre: "Rionegro", departamento: "Antioquia" },
  { nombre: "La Estrella", departamento: "Antioquia" },
  { nombre: "Apartadó", departamento: "Antioquia" },
  { nombre: "Turbo", departamento: "Antioquia" },
  { nombre: "Caldas", departamento: "Antioquia" },
  { nombre: "Copacabana", departamento: "Antioquia" },
  { nombre: "Girardota", departamento: "Antioquia" },
  { nombre: "Yumbo", departamento: "Valle del Cauca" },
  { nombre: "Palmira", departamento: "Valle del Cauca" },
  { nombre: "Buga", departamento: "Valle del Cauca" },
  { nombre: "Tuluá", departamento: "Valle del Cauca" },
  { nombre: "Cartago", departamento: "Valle del Cauca" },
  { nombre: "Buenaventura", departamento: "Valle del Cauca" },
  { nombre: "Jamundí", departamento: "Valle del Cauca" },
  { nombre: "Candelaria", departamento: "Valle del Cauca" },
  { nombre: "Florida", departamento: "Valle del Cauca" },
  { nombre: "Pradera", departamento: "Valle del Cauca" },
  { nombre: "Zarzal", departamento: "Valle del Cauca" },
  { nombre: "Roldanillo", departamento: "Valle del Cauca" },
  { nombre: "Sevilla", departamento: "Valle del Cauca" },
  { nombre: "Caicedonia", departamento: "Valle del Cauca" },
  { nombre: "El Cerrito", departamento: "Valle del Cauca" },
  { nombre: "Ginebra", departamento: "Valle del Cauca" },
  { nombre: "Guacarí", departamento: "Valle del Cauca" },
  { nombre: "Dagua", departamento: "Valle del Cauca" },
  { nombre: "La Unión", departamento: "Valle del Cauca" },
  { nombre: "Bugalagrande", departamento: "Valle del Cauca" },
  { nombre: "San Pedro", departamento: "Valle del Cauca" },
  { nombre: "Andalucía", departamento: "Valle del Cauca" },
  { nombre: "Riofrío", departamento: "Valle del Cauca" },
  { nombre: "Trujillo", departamento: "Valle del Cauca" },
  { nombre: "Barrancabermeja", departamento: "Santander" },
  { nombre: "Floridablanca", departamento: "Santander" },
  { nombre: "Girón", departamento: "Santander" },
  { nombre: "Piedecuesta", departamento: "Santander" },
  { nombre: "San Gil", departamento: "Santander" },
  { nombre: "Socorro", departamento: "Santander" },
  { nombre: "Málaga", departamento: "Santander" },
  { nombre: "Cimitarra", departamento: "Santander" },
  { nombre: "Sabana de Torres", departamento: "Santander" },
  { nombre: "Lebrija", departamento: "Santander" },
  { nombre: "Ocaña", departamento: "Norte de Santander" },
  { nombre: "Pamplona", departamento: "Norte de Santander" },
  { nombre: "Los Patios", departamento: "Norte de Santander" },
  { nombre: "Villa del Rosario", departamento: "Norte de Santander" },
  { nombre: "Tibú", departamento: "Norte de Santander" },
  { nombre: "Chiquinquirá", departamento: "Boyacá" },
  { nombre: "Sogamoso", departamento: "Boyacá" },
  { nombre: "Duitama", departamento: "Boyacá" },
  { nombre: "Paipa", departamento: "Boyacá" },
  { nombre: "Puerto Boyacá", departamento: "Boyacá" },
  { nombre: "Villa de Leyva", departamento: "Boyacá" },
  { nombre: "Aguazul", departamento: "Casanare" },
  { nombre: "Tauramena", departamento: "Casanare" },
  { nombre: "Paz de Ariporo", departamento: "Casanare" },
  { nombre: "Saravena", departamento: "Arauca" },
  { nombre: "Tame", departamento: "Arauca" },
  { nombre: "Acacías", departamento: "Meta" },
  { nombre: "Granada", departamento: "Meta" },
  { nombre: "Puerto López", departamento: "Meta" },
  { nombre: "San Martín", departamento: "Meta" },
  { nombre: "Restrepo", departamento: "Meta" },
  { nombre: "Cumaral", departamento: "Meta" },
  { nombre: "Mariquita", departamento: "Tolima" },
  { nombre: "Espinal", departamento: "Tolima" },
  { nombre: "Honda", departamento: "Tolima" },
  { nombre: "Melgar", departamento: "Tolima" },
  { nombre: "Líbano", departamento: "Tolima" },
  { nombre: "Chaparral", departamento: "Tolima" },
  { nombre: "Flandes", departamento: "Tolima" },
  { nombre: "Pitalito", departamento: "Huila" },
  { nombre: "Garzón", departamento: "Huila" },
  { nombre: "La Plata", departamento: "Huila" },
  { nombre: "Aipe", departamento: "Huila" },
  { nombre: "Campoalegre", departamento: "Huila" },
  { nombre: "Rivera", departamento: "Huila" },
  { nombre: "Dosquebradas", departamento: "Risaralda" },
  { nombre: "Santa Rosa de Cabal", departamento: "Risaralda" },
  { nombre: "La Virginia", departamento: "Risaralda" },
  { nombre: "Belén de Umbría", departamento: "Risaralda" },
  { nombre: "Chinchiná", departamento: "Caldas" },
  { nombre: "Villamaría", departamento: "Caldas" },
  { nombre: "La Dorada", departamento: "Caldas" },
  { nombre: "Calarcá", departamento: "Quindío" },
  { nombre: "La Tebaida", departamento: "Quindío" },
  { nombre: "Quimbaya", departamento: "Quindío" },
  { nombre: "Montenegro", departamento: "Quindío" },
  { nombre: "Tumaco", departamento: "Nariño" },
  { nombre: "Ipiales", departamento: "Nariño" },
  { nombre: "La Unión", departamento: "Nariño" },
  { nombre: "Túquerres", departamento: "Nariño" },
  { nombre: "Santander de Quilichao", departamento: "Cauca" },
  { nombre: "Puerto Tejada", departamento: "Cauca" },
  { nombre: "Patía", departamento: "Cauca" },
  { nombre: "Piendamó", departamento: "Cauca" },
  { nombre: "Caloto", departamento: "Cauca" },
  { nombre: "Miranda", departamento: "Cauca" },
  { nombre: "Corinto", departamento: "Cauca" },
  { nombre: "Lorica", departamento: "Córdoba" },
  { nombre: "Cereté", departamento: "Córdoba" },
  { nombre: "Sahagún", departamento: "Córdoba" },
  { nombre: "Montelíbano", departamento: "Córdoba" },
  { nombre: "Planeta Rica", departamento: "Córdoba" },
  { nombre: "Tierralta", departamento: "Córdoba" },
  { nombre: "Aguachica", departamento: "Cesar" },
  { nombre: "Bosconia", departamento: "Cesar" },
  { nombre: "Codazzi", departamento: "Cesar" },
  { nombre: "Curumaní", departamento: "Cesar" },
  { nombre: "La Jagua de Ibirico", departamento: "Cesar" },
  { nombre: "Maicao", departamento: "La Guajira" },
  { nombre: "San Juan del Cesar", departamento: "La Guajira" },
  { nombre: "Uribia", departamento: "La Guajira" },
  { nombre: "Albania", departamento: "La Guajira" },
  { nombre: "Magangué", departamento: "Bolívar" },
  { nombre: "Turbaco", departamento: "Bolívar" },
  { nombre: "Arjona", departamento: "Bolívar" },
  { nombre: "El Carmen de Bolívar", departamento: "Bolívar" },
  { nombre: "Mompox", departamento: "Bolívar" },
  { nombre: "Magdalena", departamento: "Bolívar" },
  { nombre: "Malambo", departamento: "Atlántico" },
  { nombre: "Sabanalarga", departamento: "Atlántico" },
  { nombre: "Puerto Colombia", departamento: "Atlántico" },
  { nombre: "Galapa", departamento: "Atlántico" },
  { nombre: "Ciénaga", departamento: "Magdalena" },
  { nombre: "Fundación", departamento: "Magdalena" },
  { nombre: "El Banco", departamento: "Magdalena" },
  { nombre: "Plato", departamento: "Magdalena" },
  { nombre: "Corozal", departamento: "Sucre" },
  { nombre: "Sampués", departamento: "Sucre" },
  { nombre: "Tolú", departamento: "Sucre" },
  { nombre: "San Marcos", departamento: "Sucre" },
  { nombre: "Facatativá", departamento: "Cundinamarca" },
  { nombre: "Zipaquirá", departamento: "Cundinamarca" },
  { nombre: "Chía", departamento: "Cundinamarca" },
  { nombre: "Cajicá", departamento: "Cundinamarca" },
  { nombre: "Mosquera", departamento: "Cundinamarca" },
  { nombre: "Madrid", departamento: "Cundinamarca" },
  { nombre: "Funza", departamento: "Cundinamarca" },
  { nombre: "Fusagasugá", departamento: "Cundinamarca" },
  { nombre: "Girardot", departamento: "Cundinamarca" },
  { nombre: "Tocancipá", departamento: "Cundinamarca" },
  { nombre: "Sopó", departamento: "Cundinamarca" },
  { nombre: "La Calera", departamento: "Cundinamarca" },
  { nombre: "Cota", departamento: "Cundinamarca" },
  { nombre: "Tenjo", departamento: "Cundinamarca" },
  { nombre: "Ubaté", departamento: "Cundinamarca" },
  { nombre: "Sibaté", departamento: "Cundinamarca" },
]

function normalize(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .trim()
}

export function searchCities(query: string, limit = 8): ColombiaCity[] {
  const q = normalize(query)
  if (!q) return COLOMBIA_CITIES.slice(0, limit)

  const matches: { city: ColombiaCity; score: number }[] = []
  for (const city of COLOMBIA_CITIES) {
    const nombre = normalize(city.nombre)
    const depto = normalize(city.departamento)
    if (nombre.startsWith(q)) matches.push({ city, score: 0 })
    else if (nombre.includes(q)) matches.push({ city, score: 1 })
    else if (depto.includes(q)) matches.push({ city, score: 2 })
  }
  matches.sort((a, b) => a.score - b.score || a.city.nombre.localeCompare(b.city.nombre))
  return matches.slice(0, limit).map((m) => m.city)
}
